version: "3.8"

services:
  postgres:
    image: postgis/postgis:latest
    container_name: snapp-postgres
    environment:
      - POSTGRES_USER=snapp
      - POSTGRES_PASSWORD=snapp_pass
      - POSTGRES_DB=snappdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    container_name: snapp-redis
    ports:
      - "6377:6379"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: snapp-rabbitmq
    environment:
      - RABBITMQ_USER=guset
      - RABBITMQ_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  minio:
    image: minio/minio
    container_name: snapp-minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOR_USER=minioadmin
      - MINIO_ROOR_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always

volumes:
  pgdata:
